### ISSUE TITLE
Support two empty spaces at the end of line to trigger line return 

### ISSUE THREAD

**Issue by ianbytchek** [indragiek/CocoaMarkdown#38]
If I understand correctly cmark does support this, like normal markdown syntax, but attributed string sees this break as a new paragraph. For example, the following markdown:

``` md
foo
bar

baz  
qux
```

Should render like this:

<div align="center">
<img src="https://cloud.githubusercontent.com/assets/1086845/18527986/1d62866e-7ad8-11e6-8342-3c1eb6a314b5.png">
</div>

But attributed string renders like this:

<div align="center">
<img src="https://cloud.githubusercontent.com/assets/1086845/18528164/e3716992-7ad8-11e6-8307-d0083dd6f84b.png">
</div>

Have a feeling I'm not the first one wondering about this. Anyone knows anything about this / can comment? If PR is needed, where should I start looking at?

**Comment by johngibb** [comment]
This is easy! The parser is already doing the right thing, but the renderer in this project needs to be modified.

You just need to modify `parserFoundLineBreak` in `CMAttributedStringRenderer` (https://github.com/indragiek/CocoaMarkdown/blob/master/CocoaMarkdown/CMAttributedStringRenderer.m#L217) to use a unicode line separator rather than a "\n":

    [self appendString:@"\u2028"];

Feel free to make this change and submit a PR. I'm in the middle of a project, but will try and submit a PR for this at some point in the future if you don't.

**Comment by indragiek** [comment]
This was fixed in #35
