### ISSUE TITLE
Image renders as a placeholder until user clicks on it

### ISSUE THREAD

**Issue by tsfischer** [indragiek/CocoaMarkdown#51]
Hi, I'm using the inline image functionality which was recently merged into the master branch. However, when I specify an image in markdown, I get a grey "question mark" in a box, which I see the code draws as a placeholder image. But the real image never appears until I click on that question mark, and then it instantly shows up.

Any advice? I am not fluent in NSAttributedStrings or NSTextAttachemts unfortunately.

**Comment by tsfischer** [comment]
I should have mentioned: MacOS 10.14

**Comment by tsfischer** [comment]
I found a workaround... we were using an NSTextField, which causes the above issue. Switching it to an NSTextView makes it render correctly, as in the example app. Not sure why this would matter but I'm past my problem now at least.

**Comment by jlj** [comment]
Actually `NSTextField` should not be used for markdown-related attributed string display because a text field  is a `NSControl` intended for text entry, so it has a number of limitations compared to `NSTextView.`

According to [Apple Developer Documentation](https://developer.apple.com/library/archive/documentation/TextFonts/Conceptual/CocoaTextArchitecture/TextFieldsAndViews/TextFieldsAndViews.html):

> The Field Editor
> 
> The field editor is a single NSTextView object that is shared among all the controls, including text fields, in a window. This text view object inserts itself into the view hierarchy to provide text entry and editing services for the currently active text field. **When the user shifts focus to a text field, the field editor begins handling keystroke events and display for that field**. Figure 4-3 illustrates the field editor in relation to the text field it is editing.
> 
> Figure 4-3  The field editor
> ![Figure 4-3  The field editor](https://developer.apple.com/library/archive/documentation/TextFonts/Conceptual/CocoaTextArchitecture/Art/field_editor_2x.png)

@tsfischer Can you therefore close this issue?
