### ISSUE TITLE
Make available via cocoa pods please.

### ISSUE THREAD

**Issue by jgrandelli** [indragiek/CocoaMarkdown#8]

**Comment by damienrambout** [comment]
Because this is an iOS 8+ Framework, you will have to use `CocoaPods 0.36.0` pre-release version that now supports official frameworks on iOS. Your pod will therefore be restricted to iOS 8+ projects (no breaking news here).
Check [this post](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks) for more info on Cocoapods and Frameworks.

**Comment by tomasikp** [comment]
:+1:

**Comment by arielelkin** [comment]
:+1: 

I tried writing a podspec for this library, but sadly it depends on https://github.com/jgm/cmark which depends on `cmake`, which is not installed by default.

**Comment by krodak** [comment]
https://github.com/indragiek/CocoaMarkdown/pull/19 here you go :-)

**Comment by pronebird** [comment]
As @indragiek pointed out, #19 drops submodules support. It would be great to simply add a Podspec to project.

**Comment by indragiek** [comment]
Podspec was added in #20.
